import test from 'ava';
import {Readable, Writable} from 'stream';
import {pipeline} from 'stream/promises';
import {Blowfish} from '../src/lib/blowfish';
import {createDecryptStream, decryptDownload, TrackDecryptStream} from '../src/lib/decrypt';

// ── Blowfish block-cipher test vectors (the load-bearing primitive) ──────────
test('Blowfish ECB — canonical test vectors', (t) => {
  const enc = (key: Buffer, l: number, r: number): [number, number] => {
    // encBlock is private; exercise it through the key schedule fixture instead
    return (new Blowfish(key) as any).encBlock(l >>> 0, r >>> 0);
  };
  {
    const [l, r] = enc(Buffer.alloc(8), 0, 0);
    t.is(l >>> 0, 0x4ef99745);
    t.is(r >>> 0, 0x6198dd78);
  }
  {
    const [l, r] = enc(Buffer.from('ffffffffffffffff', 'hex'), 0xffffffff, 0xffffffff);
    t.is(l >>> 0, 0x51866fd5);
    t.is(r >>> 0, 0xb85ecb8a);
  }
});

// ── Deezer stripe-decrypt, pinned to a verified real-track fixture ──────────
const SNG_ID = '3135556';
const ENC = Buffer.from(
  'bhISdaG9G22JRSjbIblgt35uY5G3127Qobu48fr/CPMTNYnRWHCaOhcAk3a16g8wWAOicTPA8aqI2Y8zEr8Ao6rHeMaOD2uI5wMeLc2/OYcQkIya7tsT/bM+EPABA2PYrPTH84JdxDZ7EcvX+bnG+MYoryNAewBMWJqNZtiNhV8nHuMule2APy39uqFBJf7mGW7EkrxUY8Zkc/yIjzqZ7+q8946OeR6+E8wmN3cCGE/YaHd6+UzxkWEwsGSE8LUF3BRwOgn0tRMgxoaAH90T67zppBDqyjll1QUtpjYOWmylPBAnZS0xoPrRq4h8Ac3kV2FhDZz0lRJ2B3SPDS1waL++sdnlOpKoyz0mjHHHF6QmRJF1eUxlPg65Pps3LRRhaD7SpfoJEDgEBGLD44SiC3p1MiUj11D8hWwey5zgEVLYY0UY3HrprvSvFUyWdm4lHqUFYYBdwijXGFrUizM2Dn5mo6PBJAAf4q3NmzRi1Q4qyFiTsvATe23Q0l2CehuubU9BZoduaJFmkrwVhLPbF0ARsxJSxNGiJ3KKaGb7jyUCi+nfTjJ/Iigaedc8RkKZJeO539S9eemFTarrVN38uKEuVS1/CL9F+LBZ4UQRrAV7T0e0pgSsandc/CZPOj5NMQuKXeTGJAlCL2SYlbG69yqVIYjubBy56staDGBiiIcObWyAqQVolETGguWDB/clOYleD/Raos3xZcxJ7ivxglbIksBV8wvYgkyvML5gq1kN4Rsz67kSMhZuAMo3tabPFdIsqURkSIuYXXhn8oYiyueHJ/8DY5rriBZumD956V4cW4cmmlk/X3Xc0qpmIVGq8C1S/l8KettCWa3Wh0Mtu0AySKc3mdnitVEd02frl/W253s+REo/yvwJd2tf4konhMQAPf5Gg1sRrvGfRggcnK+J3GQ2odbhoxR+zmel/f3SuZk8Ok7LEK7VFAfTlf01cm3B5xHXQVjGP5O7/b5dKWFBBBZXm94tzbHDkLpVw2UtDMIw2ojlnAHElKmVkmI94CXJxriPbmenRUltqrXGYRO61JZYiqAinOSzKuA1/2fWIcnNZnqBmDLfY05W49N4XIY29GG3DpPhLdRIOTkCcqKigfJNUV0QHe9kO1DBEpRXoh0Q05/khCu5jScA81JTWgTMm588LGiYQbFzSeePRyWGnGmxo4p04V3ENzpk5l5CZmXCmGbMfSyXnMS9PmtJ+k+26c28KgZEI82w/5dRczLcYNHFuY2T5vRwDc2vAtoqwVNpFi/LH+S6sei1VbUFS6DRHkS4Rf7v58t4ynXuqds+t1MPjRSFH75OC1pEW6XdEQBJAIJxqMj9lnpxlPPP//DrJD55abC9vwLx8KMJQYavqrFzsDvrCfpAQbMHVvJ2mknOLG1vjKh+TW1ezb/SMFAhr7JJd9gQz5Id2PYXCrA89jnvaTrShWE0eBrhNcFR8z3/pMUr/NmQm2OrpUHTSzaq79gwV5hBOdWYt9gt0X4jN5bmLJ1Iv6xrcSgaSfDDqEt9oI/6DatwDHDtU9M3C+PruOPQ3d81/gmhRb0jx6jbvb4fQuLI6iRw0uIgs/gWgNJhuplNOLcg9/luMzYegfzGPfFKL4ndOQEze1WKWltat9W9b5M0i2x/2C1rw4Ij8oaQTdecH+nITi/NdbCyDfTqWyquVVLzxuta/o25ebF4GEvdvP54rMXOp43oJz/LBZfW78DiF+vLPHCqFs9tFyux45/xQXoTIeVqlIH7Gs0H481CG3R24ppKr/DR0PGO0DpWHiCqtZIb/V1W2xr3P6CHS3o/k6sny2w/i6+QwYX/D2boNiOKK3OxxefbBZzeRFnM1vVyfe3mjN7+8TXvQKSfvdhj2pi7Jjp8zlg3finDAjwUh45SDz3qxi+iV7yKNdboHhktJ/R89vpFsm9nU+brMxYGqV9FnkU9P/hvOpDAAgY0KmNazyHpfBfUN4gjmDwZjkDFe43rMt1ByhF0D7YWyaPQ8y7N1kg2nl1E30M8YhUx4HInm7/vKUYORwED8s0RF1nUY7ZqHi0B9JTztMqRMMdzn9qmiKc5JFE8nMwQm14drWAfad48eeBstZ/klRGRmzQUgzpdPxJtgCsG0Fpkb24cyqYaXncyf84C44t9UyU7As4XJS2n13fEkxmI8Sa1/2yaZzv5tMF+3iv3qwZ9wUQplC/ZC8tvPRZiAid45ChBO3BZVHcDFwkzygcle1U9bBdkwxcq8cVRYIRczKAUgMCsaiJ0Mcr+soJP62xx4UekzQeDnTCmMvsCRPn2KZNgTLQJuLh4MsEmqHZnezqT4pjrFLLr4tA30WUUC8yNpmnSQcXs1VilO04SHPAaYzlWVw8X9zxCgEhfDVfyTkCCEZS2P5kVy5LI6dmy7zWgUBAaNJnM7hqp2s94cYSFlftk+pydh3gtSb5O2SJyid8aaNxsyxr84EUH2JOkXCefxHjAv8DzEB5Lu0mPlnATAhuNDwBKN8hASjLOJSbRvUHzkZuY0HHMtrKwUHIZnj5QR75nCb6X1OSbCUNlDTZYAL3/W0Ap/zW6CTLbB9urTc3/XuV/JrPo00VfKpesBguGmqQh7kF4nbnYnIGipTzYUQLcfoe/auRzBvmgM2PnczJCCx2y9G5r43apbI7fzIdOmY1D6Pm0y0FptliOfY5LkMMYAKpdIufJ5U00Dmkibxdjm6gXyCcaEEHHmc9sFO08cZJSO9Y5C62/yYmmfU4=',
  'base64',
);
const DEC = Buffer.from(
  'ZkxhQwAAACIQABAAAAAOADf7CsRC8ACYWzzA1c/uJapgidBwPyIlAgoDAwABngAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABrAAAAAAAAAK4+AQAAAAAAAADXAAAAAAAAAYMt0QAAAAAAAAFCAAAAAAAAApzcwQAAAAAAAAGuAAAAAAAAA8aUoQAAAAAAAAIaAAAAAAAABPHCAQAAAAAAAAKFAAAAAAAABhP2cQAAAAAAAALxAAAAAAAABzDDMQAAAAAAAANdAAAAAAAACEmhUQAAAAAAAAPIAAAAAAAACWsyYQAAAAAAAAQ0AAAAAAAACmseQQAAAAAAAASgAAAAAAAAC53d8QAAAAAAAAULAAAAAAAADMwqcQAAAAAAAAV3AAAAAAAADdfZAQAAAAAAAAXjAAAAAAAADue88QAAAAAAAAZOAAAAAAAAEAGvoQAAAAAAAAa6AAAAAAAAESk2EQAAAAAAAAcmAAAAAAAAEjG0cQAAAAAAAAeRAAAAAAAAE0zj0QAAAAAAAAf9AAAAAAAAFGCJIQAAAAAAAAhpAAAAAAAAFXfPEQAAAAAAAAjUAAAAAAAAFoudAQAAAAAAAAlAAAAAAAAAF6q3wQAAQAACggAAAAcmVmZXJlbmNlIGxpYkZMQUMgMS4zLjEgMjAxNDExMjUAAAAAgQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
  'base64',
);

test('decryptDownload — first stripe matches the verified fixture', (t) => {
  const out = decryptDownload(ENC, SNG_ID);
  t.is(out.length, ENC.length);
  t.true(out.equals(DEC), 'decrypted first 2048 bytes differ from the known-good output');
});

test('decryptDownload — plaintext (non-3rd) chunks pass through', (t) => {
  // chunk index 1 is never encrypted → identical in/out
  const src = Buffer.concat([Buffer.alloc(2048), Buffer.from('the quick brown fox'.repeat(200)).subarray(0, 2048)]);
  const out = decryptDownload(src, SNG_ID);
  t.true(out.subarray(2048).equals(src.subarray(2048)));
});

test('TrackDecryptStream === decryptDownload for arbitrary chunking', (t) => {
  const whole = Buffer.concat([ENC, ENC, ENC.subarray(0, 500)]); // 3 stripes + tail
  const batch = decryptDownload(whole, SNG_ID);
  const ds = new TrackDecryptStream(SNG_ID);
  const parts: Buffer[] = [];
  for (let i = 0; i < whole.length; i += 777) parts.push(ds.write(whole.subarray(i, i + 777)));
  parts.push(ds.final());
  t.true(Buffer.concat(parts).equals(batch));
});

test('createDecryptStream (Transform) === decryptDownload', async (t) => {
  const whole = Buffer.concat([ENC, ENC, ENC, ENC.subarray(0, 900)]); // 4 stripes + tail
  const batch = decryptDownload(whole, SNG_ID);

  const out: Buffer[] = [];
  const sink = new Writable({
    write(c: Buffer, _e, cb) {
      out.push(c);
      cb();
    },
  });
  // odd read sizes to exercise the carry buffer
  await pipeline(Readable.from(chunkBy(whole, 613)), createDecryptStream(SNG_ID), sink);
  t.true(Buffer.concat(out).equals(batch));
});

test('createDecryptStream — startChunk resumes stripe phase correctly', (t) => {
  const whole = Buffer.concat([ENC, ENC, ENC]); // stripes 0,1,2 — 0 and 2 would be... 0 only (0%3)
  const full = decryptDownload(whole, SNG_ID);
  // resume from byte 2048 (chunk index 1): decrypt the remaining two stripes with startChunk=1
  const engine = new TrackDecryptStream(SNG_ID, 1);
  const tail = Buffer.concat([engine.write(whole.subarray(2048)), engine.final()]);
  t.true(tail.equals(full.subarray(2048)));
});

function* chunkBy(buf: Buffer, n: number) {
  for (let i = 0; i < buf.length; i += n) yield buf.subarray(i, i + n);
}
